### ISSUE TITLE
weewx won't start version 0.4

### ISSUE THREAD

**Issue by captain-coredump** [matthewwall/weewx-meteotemplate#2]
I just installed version 0.4 from the readme instructions, and weewx errors out on startup:

# weewxd /etc/weewx/weewx.conf
Traceback (most recent call last):
  File "/usr/bin/weewxd", line 64, in <module>
    weewx.engine.main(options, args)
  File "/usr/share/weewx/weewx/engine.py", line 841, in main
    engine = engine_class(config_dict)
  File "/usr/share/weewx/weewx/engine.py", line 76, in __init__
    self.loadServices(config_dict)
  File "/usr/share/weewx/weewx/engine.py", line 140, in loadServices
    self.service_obj.append(weeutil.weeutil._get_object(svc)(self, config_dict))
  File "/usr/share/weewx/user/meteotemplate.py", line 106, in __init__
    config_dict, 'wx_binding')
NameError: global name 'config_dict' is not defined

**Comment by matthewwall** [comment]
fixed at commit 2103dab
